### ISSUE TITLE
`Open browser` sometimes fails with Google Chrome with error `Cannot call method 'indexOf' of undefined`

### ISSUE THREAD

**Issue by spooning** [robotframework/OldSeleniumLibrary#187]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=187) by huangyongde on 12 Apr 2011_

library version:2.6
python version:2.6
operating system:windows xp

i've tried to "open browser" to visit www.google.com and www.yahoo.com,but it said

"Exception: Cannot call method 'indexOf' of undefined"

here are my test script:

from SeleniumLibrary import SeleniumLibrary
def test_login(params=None):
    _Extend_SeleniumLibrary = SeleniumLibrary(timeout=10)
    url_list = ['http://www.google.com','http://www.yahoo.com'
    for url in url_list:
        _Extend_SeleniumLibrary.open_browser(url, 'googlechrome') 
        _Extend_SeleniumLibrary.maximize_browser_window()

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=187#c1) by huangyongde on 12 Apr 2011_

sorry,miss ']' at line 4
    url_list = ['http://www.google.com','http://www.yahoo.com'

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=187#c2) by @pekkaklarck on 13 Apr 2011_

First of all, if you are planning to use SeleniumLibrary with Robot Framework there's no need to write this kinf of extra wrapper library. You can just create a test that uses the keywords from SeleniumLibrary directly, for example:

**_Settings**_
Library  SeleniumLibrary  timeout=10

**_TestCases**_
Example
    Open Browser  <a href="http://www.google.com" rel="nofollow">http://www.google.com</a>
    Open Browser  <a href="http://www.yahoo.com" rel="nofollow">http://www.yahoo.com</a>

The error you got nevertheless looks pretty weird. Could you run tests with debug level (i.e. use command line option `--loglevel DEBUG`) and copy the traceback that is logged with debug level here?

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=187#c3) by huangyongde on 14 Apr 2011_

thanks pekka.klarck,here are my traceback records:

19:15:06.233 FAIL Cannot call method 'indexOf' of undefined
19:15:06.233 DEBUG Traceback (most recent call last):
 File "&lt;string&gt;", line 2, in open_browser
 File "D:\Autotest\Core\SeleniumLibrary\runonfailure.py", line 40, in _run_on_failure_wrapper
   return method(_args, *_kwargs)
 File "D:\Autotest\Core\SeleniumLibrary__init__.py", line 395, in open_browser
   self._selenium.open(url, ignoreResponseCode=True)
 File "D:\Autotest\Core\SeleniumLibrary\selenium.py", line 772, in open
   self.do_command("open", [url,ignoreResponseCode])
 File "D:\Autotest\Core\SeleniumLibrary\selenium.py", line 217, in do_command
   raise Exception, data

btw ,i think use wrapper lib is more flexible than tsv/txt textformat  :)

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=187#c4) by @pekkaklarck on 3 May 2011_

I tested that I got the same "Cannot call method 'indexOf' of undefined" with the following test data:

**_Settings**_
Library  SeleniumLibrary

**_TestCases**_
Example
    Open Browser  <a href="http://www.google.com" rel="nofollow">http://www.google.com</a>  googlechrome

Using Chrome to test pages on localhost, where also my Selenium server was running, succeeded. I did a fast search with this error and found lot of results. It thus seems that this is a common problem in Selenium with Google Chrome. Unfortunately I don't have time to investigate this further in the near future. If you are willing to investigate this please keep this issue updated.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=187#c6) by @yanne on 8 Aug 2011_

I have not been able to reproduce this and I anyway think that this is a Selenium problem. We will upgrade to Selenium server 2.3 in next release and hopefully this problem disappears.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=187#c7) by shalu.... on 24 Aug 2011_

Hi we are running version 2.4 and still having the same issue.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=187#c8) by @pekkaklarck on 25 Aug 2011_

You definitely should upgrade to the latest SeleniumLibrary version (2.8 at the moment). It contains the latest Selenium version and thus has also the latest Selenium fixes.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=187#c9) by shalu.... on 25 Aug 2011_

Hi I  am running selenium server version 2.4 now uppgraded to 2.5 but 2.8 selenium library itself and still having issues.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=187#c10) by @pekkaklarck on 25 Aug 2011_

I did a search again and found an issue about this in Selenium's tracker:
<a href="http://jira.openqa.org/browse/SRC-740" rel="nofollow">http://jira.openqa.org/browse/SRC-740</a>

It seems that this was once fixed in Selenium but later decided that the fix wasn't good and some --disable-web-security option should be used instead. Apparently this isn't an option for Selenium Server but so called "browser configuration option". Unfortunately I don't know how they can be passed using Selenium 1 RC API or is that possible at all.

I reopen this issue but don't have time to look at this any more deeply in the near future. If someone can find a way how to pass the --disable-web-security option or figures out some other solution, we surely will apply the fix in the next release. To start searching for more information you can do the same search I did:
<a href="http://www.google.com/search?q=selenium+googlechrome+Cannot+call+method+&#37;27indexOf&#37;27+of+undefined" rel="nofollow">http://www.google.com/search?q=selenium+googlechrome+Cannot+call+method+&#37;27indexOf&#37;27+of+undefined</a>

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=187#c11) by @yanne on 14 Dec 2011_

Recent versions of Selenium RC support giving browser options, so I think this can be fixed by just hard coding --disable-web-security if the used browser is Chrome

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=187#c12) by @yanne on 14 Dec 2011_

This issue was updated by <a href="https://code.google.com/p/robotframework-seleniumlibrary/source/detail?r=0639cfa52553">revision 0639cfa52553</a>.
