### ISSUE TITLE
Do we need to start selenium server to use Selenium2Library in RIDE pls?

### ISSUE THREAD

**Issue by spooning** [robotframework/OldSeleniumLibrary#223]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=223) by scottyan... on 28 Dec 2011_

Environment Info:
1. Python26 Jython2.5.1 WindowsXP 
2. we use RF with Seleniumlibrary2.5.7 + selenium-server2.0 fluently.

________Question1_____________
Do we need to start selenium server to use Selenium2Library in RIDE pls?

________Trial Steps_____________
1. put the Selenium2Library folder to this path: C:\Python26\Lib\site-packages
2. create a new project in RIDE and import the library Selenium2Library to test suite
3. write test case: the keyword "open browser" has been hightlighted with bold blue style and the tooltip shows the keyword if from selenium2library.
    open browser xxx xxx
## FAIL: No keyword with name 'Open Browser' found.

20111228 16:07:26.315   ERROR   Invalid syntax in file 'd:\ride\wu3\suites\Test1\Array.tsv' in table 'Setting': Importing test library 'Selenium2Library' failed: ImportError: No module named api
PYTHONPATH: ['C:\Python26\Lib\site-packages\Selenium2Library\lib\decorator-3.3.2', 'C:\Python26\Lib\site-packages\Selenium2Library\lib\selenium-2.8.1\py', 'C:\Python26\Lib\site-packages\Selenium2Library\lib\decorator-3.3.2', 'C:\Python26\Lib\site-packages\Selenium2Library\lib\selenium-2.8.1\py', 'C:\Python26\Lib\site-packages', 'C:\Python26\Lib\site-packages\robot\libraries', 'C:\jython2.5.1\Lib', '**classpath**', '**pyclasspath**/', 'C:\jython2.5.1\Lib\site-packages', 'D:\RIDE\wu3\lib', '.']
CLASSPATH: C:\jython2.5.1\jython.jar;C:\Python26\Lib;
Traceback (most recent call last):
 File "C:\Python26\Lib\site-packages\robot\utils\importing.py", line 94, in _import
   __import__(name)
 File "C:\Python26\Lib\site-packages\Selenium2Library__init__.py", line 8, in &lt;module&gt;
   from keywords import *
 File "C:\Python26\Lib\site-packages\Selenium2Library\keywords__init__.py", line 1, in &lt;module&gt;
   from _logging import _LoggingKeywords
 File "C:\Python26\Lib\site-packages\Selenium2Library\keywords_logging.py", line 4, in &lt;module&gt;

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=223#c1) by scottyan... on 8 Jan 2012_

## Also, it showed us this error info by using the official demo(login tests) without starting selenium server.

Import Selenium2Library module failed.
Please make sure you have Selenium2Library installed.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=223#c2) by @pekkaklarck on 10 Jan 2012_

First of all, this tracker is for the old SeleniumLibrary. Selenium2Library has its own tracker in its project pages on GitHub. Second, at least with SeleniumLibrary you always need to have the server running. I don't know do you always need it with Selenium2Library.
