### ISSUE TITLE
Unable to Select a Tab Pane inside another Tab Pane

### ISSUE THREAD

**Issue by spooning** [robotframework/OldSeleniumLibrary#67]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=67) by nipunkj... on 14 Dec 2009_

I am new to Robot framework.
I wanted to select a Table column inside a Tab that itself is inside 
another Tab which contains more than one tab.
Steps:
1) A table inside a Tab (say contacts) that is inside another tab (say abc)
2) Get Selected Tab Label  gives the value as "abc".
3) Select Tab Pane "contacts"/ Select Tab "contacts".

Unable to select this Tab and hence unable to Select the column inside as 
well.

I am using Windows XP.
Python version: 2.6.4
Jython version: 2.5.1
Robot Framework: 2.1.2

---

Stack Trace:
KEYWORD: SwingLibrary.Select Tab Pane contacts  
Documentation: Sets a tab pane as the current context. 
Start / End / Elapsed: 20091215 11:26:14.153 / 20091215 11:26:19.165 / 
00:00:05.012 
11:26:14.153 TRACE Arguments: [ contacts ] 
11:26:19.165 FAIL Wait for "contacts" subcomponent to be displayed 
11:26:19.165 DEBUG java.lang.RuntimeException: 
        at 
org.robotframework.javalib.library.AnnotationLibrary.retrieveInnerException
(AnnotationLibrary.java:83)
        at org.robotframework.javalib.library.AnnotationLibrary.runKeyword
(AnnotationLibrary.java:65)
        at SwingLibrary.runKeyword(SwingLibrary.java:32)
Caused by: org.netbeans.jemmy.TimeoutExpiredException: Wait for "contacts" 
subcomponent to be displayed
        at org.netbeans.jemmy.Waiter.waitAction(Waiter.java:147)
        at org.netbeans.jemmy.operators.ContainerOperator.waitSubComponent
(ContainerOperator.java:298)
        at org.netbeans.jemmy.operators.JTabbedPaneOperator.&lt;init&gt;
(JTabbedPaneOperator.java:96)
        at org.netbeans.jemmy.operators.JTabbedPaneOperator.&lt;init&gt;
(JTabbedPaneOperator.java:108)
        at org.robotframework.swing.tab.TabbedPaneOperator.&lt;init&gt;
(TabbedPaneOperator.java:12)
        at 
org.robotframework.swing.tab.TabPaneOperatorFactory.createOperatorByName
(TabPaneOperatorFactory.java:46)
        at 
org.robotframework.swing.tab.TabPaneOperatorFactory.createOperatorByName
(TabPaneOperatorFactory.java:29)
        at 
org.robotframework.swing.factory.IdentifierParsingOperatorFactory.nameArgum
ent(IdentifierParsingOperatorFactory.java:33)
        at org.robotframework.swing.arguments.ArgumentParser.parseArgument
(ArgumentParser.java:35)
        at 
org.robotframework.swing.factory.IdentifierParsingOperatorFactory.createOpe
rator(IdentifierParsingOperatorFactory.java:25)
        at 
org.robotframework.swing.tab.TabPaneOperatorFactory.createOperator
(TabPaneOperatorFactory.java:36)
        at org.robotframework.swing.keyword.tab.TabKeywords.selectTabPane
(TabKeywords.java:60)
        at org.robotframework.javalib.reflection.KeywordInvoker.invoke
(KeywordInvoker.java:52)
        at 
org.robotframework.javalib.beans.annotation.AnnotationKeywordExtractor$1.ex
ecute(AnnotationKeywordExtractor.java:58)
        at 
org.robotframework.javalib.library.KeywordFactoryBasedLibrary.runKeyword
(KeywordFactoryBasedLibrary.java:39)
        at org.robotframework.javalib.library.AnnotationLibrary.runKeyword
(AnnotationLibrary.java:63)
        ... 166 more 

---

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=67#c1) by @pekkaklarck on 14 Dec 2009_

Based on the stacktrace this issue seems to be related to SwingLibrary and not
SeleniumLibrary. Please submit a new issue to SwingLibrary's tracker at 
<a href="https://code.google.com/p/robotframework-swinglibrary/issues/list" rel="nofollow">https://code.google.com/p/robotframework-swinglibrary/issues/list</a>

SwingLibrary 1.1 development is currently ongoing so if this issue is easy to fix it
might still make it into that release.
