### ISSUE TITLE
Document that if Selenium Server is restarted it may need to use different port

### ISSUE THREAD

**Issue by spooning** [robotframework/OldSeleniumLibrary#76]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=76) by jerry57 on 21 Jan 2010_

If I run multiple test suites with the following commandline, the first
test in the second suite fails with "BadStatusLine".  Adding a sleep as the
first command in the third suite, first test results in ALL of it's tests
failing with "Could not connect to Selenium server in 10 seconds. Please
make sure Selenium server is running."

pybot -d ~/junk/output/ JunkGoogleOne.html JunkGoogleTwo.html
JunkGoogleThree.html 

All of these suites run normally if run one at a time though.  I have
sample test suites and results logs that will be attached.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=76#c1) by jerry57 on 21 Jan 2010_

Sorry, forgot to post versions
RobotFramework 2.1.2
RobotFramework-SeleniumLibrary 2.2.2
python 2.6.1
jython 2.5.1
OS Mac OS X 10.6.2

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=76#c2) by @pekkaklarck on 22 Jan 2010_

The problem is most likely related you starting/stopping the SeleniumServer in every
test suite. Could you start the server before running tests and stop it afterwards
instead? Or alternatively use **init**.html file and start/stop the server there.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=76#c3) by jerry57 on 26 Jan 2010_

We have implemented using **init**.html via arguments file for now, but would really
like to get this problem resolved.  Agreed that the problem is in stop/starting the
selenium server in each suite, but the startup does not appear to be happening
quickly enough for the tests to begin.  Hence the "BadStatusLine" error that is up
channeled.

I would be more than happy to test out any resolutions in the future as I understand
that you do not have access to any Mac machines right now.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=76#c4) by @pekkaklarck on 26 Jan 2010_

It's possible that the problem is not in starting itself but in stopping the server
and then starting it again. The port used by the server might not be made free
immediately and thus restarting may fail or just take more time. Unfortunately I
don't have time to investigate this at the moment but here are few things you could try:

1) See does using different port in the second suite help. Notice that you need to
use the same port both when importing the library and starting the server until <a class="closed_ref" href="https://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=71" title="`Start Selenium Server` should use the port given to the library when it is taken into use"> issue
71 </a> is fixed.

2) Find the Selenium server log and see does it contain any interesting information.
See the keyword's doc about where it is written to (and <a class="closed_ref" href="https://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=78" title="`Start Selenium Server` keyword should log the path to the Seleniun server log (and it's doc should have usage examples)"> issue 78 </a> about the keyword
also logging that information).

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=76#c5) by jerry57 on 28 Jan 2010_

It appears that the problem is in timing.  The previous server isn't shutting down
fast enough to free up the port so that the new server can bind to it:

15:51:39.976 WARN - Failed to start: SocketListener0@&#8288;0.0.0.0:4444
Exception in thread "main" java.net.BindException: Selenium is already running on
port 4444. Or some other service is.
    at org.openqa.selenium.server.SeleniumServer.start(SeleniumServer.java:378)
    at org.openqa.selenium.server.SeleniumServer.boot(SeleniumServer.java:224)
    at org.openqa.selenium.server.SeleniumServer.main(SeleniumServer.java:188)
15:51:40.092 INFO - Shutting down...

The above is from the selenium log file.

I was not able to test using different ports, I can't seem to get the library import
syntax and start selenium server syntax correct.  Always reports "invalid time
string", "start selenium server keyword not found".  Can you send me samples of what
needs to be in the tests that I sent to test this and I will gladly give it a try and
let you know the results.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=76#c6) by @yanne on 3 Feb 2010_

The port is 3rd argument that the SeleniumLibrary accepts when taken into use. I
updated the document with an example:

<a href="http://robotframework-seleniumlibrary.googlecode.com/svn/trunk/doc/SeleniumLibrary.html" rel="nofollow">http://robotframework-seleniumlibrary.googlecode.com/svn/trunk/doc/SeleniumLibrary.html</a>

In short, taking library into use with

Library | SeleniumLibrary | | | 4455 

should start the server in port 4455. Notice that there are two empty cells, for
timeout and host, and defaults for those are used.

In addition, you must use the Start Selenium Server like this:

| Start Selenium Server | -port | 4455 |

There a request (<a class="closed_ref" href="https://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=71" title="`Start Selenium Server` should use the port given to the library when it is taken into use"> issue 71 </a>) about simplifying this so that Start Selenium Server would
always use the same port as library import, but currentöy the port must be specifies
twice.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=76#c7) by jerry57 on 3 Feb 2010_

Thanks for the instructions, this helped greatly.  I have run the sample test suites
I sent before using different ports and there were no problems.  The selenium server
starts up and shuts down normally each time and the suites can all be listed on the
commandline.  This work around will work much better for us than the directory init file.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=76#c8) by @pekkaklarck on 3 Feb 2010_

Awesome!

To prevent similar problems in the future, we probably should document this behavior
somehow. Would adding a note to the doc of `Start Selenium Server` keyword be enough
or should this be mentioned somewhere else too?

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=76#c9) by jerry57 on 3 Feb 2010_

Adding a note to the 'Start Selenium Server' should be enough as long as it mentions
using different ports when suites will be run back to back.  The only other place you
might want to note it would be in the suite creation section.  Just in case people
don't pay attention to the keyword section.  I think most would be okay with the
keyword section though.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=76#c12) by @yanne on 9 Feb 2010_

Added some docs on this subject in <a href="https://code.google.com/p/robotframework-seleniumlibrary/source/detail?r=314">r314</a>, would be cool if someone would check whether
it's clear enough.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=76#c13) by @pekkaklarck on 9 Feb 2010_

jerry57, could you take a look at the new doc? It's available at
<a href="http://robotframework-seleniumlibrary.googlecode.com/svn/trunk/doc/SeleniumLibrary.html#Start&#37;20Selenium&#37;20Server" rel="nofollow">http://robotframework-seleniumlibrary.googlecode.com/svn/trunk/doc/SeleniumLibrary.html#Start&#37;20Selenium&#37;20Server</a>

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=76#c14) by jerry57 on 9 Feb 2010_

I think this will be fine as long as you keep the references in the import library so
that it is clear how to state the port.  THANKS
