### ISSUE TITLE
Support Firefox 3.6 by updating the embedded Selenium Server to 1.0.3 version

### ISSUE THREAD

**Issue by spooning** [robotframework/OldSeleniumLibrary#99]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=99) by jrvilda on 24 Feb 2010_

KEYWORD: SeleniumLibrary.Open Browser <a href="http://www.google.com" rel="nofollow">http://www.google.com</a>, firefox
Documentation:  Opens a new browser instance to given url.
Start / End / Elapsed:  20100224 13:09:47.000 / 20100224 13:10:23.467 /
00:00:36.467
13:09:47.015    TRACE   Arguments: [ <a href="http://www.google.com" rel="nofollow">http://www.google.com</a> | firefox ]
13:10:23.342    INFO    Opening browser 'firefox' to base url
'http://www.google.com'
13:10:23.453    FAIL    Could not connect to Selenium Server in 10 seconds.
Please make sure Selenium Server is running.
13:10:23.453    DEBUG   Traceback (most recent call last):
 File "c:\python26\lib\site-packages\SeleniumLibrary__init__.py", line
275, in open_browser
   self._connect_to_selenium_server()
 File "c:\python26\lib\site-packages\SeleniumLibrary__init__.py", line
294, in _connect_to_selenium_server
   raise RuntimeError("Could not connect to Selenium Server in 10 seconds. "

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=99#c1) by @pekkaklarck on 24 Feb 2010_

This could be a Selenium problem (I'm not sure does the version bundled with SeLib
2.3 work with Fx 2.6 yet) but the fact connection to Selenium Server fails makes me
wonder is it really started. Have you tested does running tests work with other browsers?

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=99#c2) by jrvilda on 24 Feb 2010_

yes, in the version 3.5 works well.
With firefox 3.6 is running but does not display the window

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=99#c3) by @pekkaklarck on 25 Feb 2010_

The browser is actually launched by the Selenium Server. The error message you
provided shows that you cannot connect to the Selenium Server at all, and I don't
know how that could be affected by the browser version.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=99#c4) by jrvilda on 25 Feb 2010_

problems when launching the browser with the "-chrome chrome: / / killff / content /
kill.html"

selenium-library 2.3 has been released on February 15
selenium-rc 1.0.3 with support firefox 3.6 has been released on 23 February.

Can I change the selenium-server.jar  Library 2.3 RC for 1.0.3?

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=99#c5) by jrvilda on 25 Feb 2010_

This is de report :
-+KEYWORD: SeleniumLibrary.Start Selenium Server  
Documentation: Starts the Selenium Server provided with SeleniumLibrary. 
Start / End / Elapsed: 20100225 18:31:11.875 / 20100225 18:31:11.890 / 00:00:00.015 
18:31:11.875 TRACE Arguments: [  ] 
18:31:11.890 INFO Selenium Server started to port 4444. Log is written to
e:\documents and settings\administrador\logs\20100225\selenium_server_log.txt. 
18:31:11.890 TRACE Return: None 

+-KEYWORD: SeleniumLibrary.Open Browser <a href="http://www.google.com" rel="nofollow">http://www.google.com</a>, firefox  
Documentation: Opens a new browser instance to given url. 
Start / End / Elapsed: 20100225 18:31:11.890 / 20100225 18:31:46.640 / 00:00:34.750 
18:31:11.890 TRACE Arguments: [ <a href="http://www.google.com" rel="nofollow">http://www.google.com</a> | firefox ] 
18:31:46.640 INFO Opening browser 'firefox' to base url 'http://www.google.com' 
18:31:46.640 FAIL Failed to start new browser session: Unable to delete file
E:\DOCUME~1\ADMINI~1\CONFIG~1\Temp\customProfileDir9fc92fab0d624fbbbd8ddc973350973b\parent.lock

18:31:46.640 DEBUG Traceback (most recent call last):
 File "e:\python26\lib\site-packages\SeleniumLibrary__init__.py", line 275, in
open_browser
   self._connect_to_selenium_server()
 File "e:\python26\lib\site-packages\SeleniumLibrary__init__.py", line 288, in
_connect_to_selenium_server
   self._selenium.start()
 File "e:\python26\lib\site-packages\SeleniumLibrary\selenium.py", line 189, in start
   result = self.get_string("getNewBrowserSession", [self.browserStartCommand,
self.browserURL, self.extensionJs])
 File "e:\python26\lib\site-packages\SeleniumLibrary\selenium.py", line 221, in
get_string
   result = self.do_command(verb, args)
 File "e:\python26\lib\site-packages\SeleniumLibrary\selenium.py", line 217, in
do_command
   raise Exception, data

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=99#c6) by jrvilda on 25 Feb 2010_

18:31:12.093 INFO - Java: Sun Microsystems Inc. 14.3-b01
18:31:12.093 INFO - OS: Windows XP 5.1 x86
18:31:12.109 INFO - v1.0.1 [2696], with Core v@&#8288;VERSION@&#8288; [@&#8288;REVISION@&#8288;]
18:31:12.218 INFO - Version Jetty/5.1.x
18:31:12.218 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
18:31:12.218 INFO - Started HttpContext[/selenium-server,/selenium-server]
18:31:12.218 INFO - Started HttpContext[/,/]
18:31:12.359 INFO - Started SocketListener on 0.0.0.0:4444
18:31:12.359 INFO - Started org.mortbay.jetty.Server@&#8288;c40c80
18:31:12.593 INFO - Checking Resource aliases
18:31:12.609 INFO - Command request: getNewBrowserSession[*firefox,
<a href="http://www.google.com" rel="nofollow">http://www.google.com</a>, ] on session null
18:31:12.609 INFO - creating new remote session
18:31:12.796 INFO - Allocated session 9fc92fab0d624fbbbd8ddc973350973b for
<a href="http://www.google.com" rel="nofollow">http://www.google.com</a>, launching...
18:31:12.875 INFO - Preparing Firefox profile...
18:31:34.359 ERROR - Failed to start new browser session, shutdown browser and clear
all session data
java.lang.RuntimeException: Firefox refused shutdown while preparing a profile
    at
org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher.waitForFullProfileToBeCreated(FirefoxChromeLauncher.java:311)
    at
org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher.populateCustomProfileDirectory(FirefoxChromeLauncher.java:106)
    at
org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher.launch(FirefoxChromeLauncher.java:83)
    at
org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher.launchRemoteSession(FirefoxChromeLauncher.java:350)
    at
org.openqa.selenium.server.browserlaunchers.FirefoxLauncher.launchRemoteSession(FirefoxLauncher.java:98)
    at
org.openqa.selenium.server.BrowserSessionFactory.createNewRemoteSession(BrowserSessionFactory.java:357)
    at
org.openqa.selenium.server.BrowserSessionFactory.getNewBrowserSession(BrowserSessionFactory.java:122)
    at
org.openqa.selenium.server.BrowserSessionFactory.getNewBrowserSession(BrowserSessionFactory.java:84)
    at
org.openqa.selenium.server.SeleniumDriverResourceHandler.getNewBrowserSession(SeleniumDriverResourceHandler.java:699)
    at
org.openqa.selenium.server.SeleniumDriverResourceHandler.doCommand(SeleniumDriverResourceHandler.java:393)
    at
org.openqa.selenium.server.SeleniumDriverResourceHandler.handleCommandRequest(SeleniumDriverResourceHandler.java:364)
    at
org.openqa.selenium.server.SeleniumDriverResourceHandler.handle(SeleniumDriverResourceHandler.java:125)
    at org.mortbay.http.HttpContext.handle(HttpContext.java:1530)
    at org.mortbay.http.HttpContext.handle(HttpContext.java:1482)
    at org.mortbay.http.HttpServer.service(HttpServer.java:909)
    at org.mortbay.http.HttpConnection.service(HttpConnection.java:820)
    at org.mortbay.http.HttpConnection.handleNext(HttpConnection.java:986)
    at org.mortbay.http.HttpConnection.handle(HttpConnection.java:837)
    at org.mortbay.http.SocketListener.handleConnection(SocketListener.java:245)
    at org.mortbay.util.ThreadedServer.handle(ThreadedServer.java:357)
    at org.mortbay.util.ThreadPool$PoolThread.run(ThreadPool.java:534)
Caused by:
org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher$FileLockRemainedException:
Lock file still present!
E:\DOCUME~1\ADMINI~1\CONFIG~1\Temp\customProfileDir9fc92fab0d624fbbbd8ddc973350973b\parent.lock
    at
org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher.waitForFileLockToGoAway(FirefoxChromeLauncher.java:269)
    at
org.openqa.selenium.server.browserlaunchers.FirefoxChromeLauncher.waitForFullProfileToBeCreated(FirefoxChromeLauncher.java:309)
    ... 20 more
18:31:46.640 INFO - Got result: Failed to start new browser session: Unable to delete
file
E:\DOCUME~1\ADMINI~1\CONFIG~1\Temp\customProfileDir9fc92fab0d624fbbbd8ddc973350973b\parent.lock
on session null

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=99#c7) by jrvilda on 25 Feb 2010_

changing the selenium-rc server.jar of selenium for selenium-server.jar of
selenium-library is operating correctly.

Can you give any problem?

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=99#c8) by @pekkaklarck on 25 Feb 2010_

If I've understood it correctly, Firefox 3.6 isn't supported by Se 1.0.1 that SeLib
2.3 uses. Se 1.0.3 that was released few days ago (right after 1.0.2) ought to fix
this. We've already decided to release SeLib 2.3.1 with Se 1.0.3 next week. Simply
using the Selenium Server that is part of Se 1.0.3, like jrvilda did, is a workaround
for this problem until that.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=99#c9) by @yanne on 28 Feb 2010_

Upgraded to selenium 1.0.3 in <a href="https://code.google.com/p/robotframework-seleniumlibrary/source/detail?r=450">r450</a>

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=99#c11) by radekw13 on 1 Mar 2010_

I have one problem on Ubuntu 9.10. More than 50&#37; of the time selenium does not open
the port in 10 seconds causing the test suite to fail. I started the jar manually
many times and most of the time there is a delay in opening the listener connection.

Can someone confirm?

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=99#c12) by @yanne on 2 Mar 2010_

I have run our own acceptance tests a handful of times with no problems.

However, it is easy to increase this timeout. Radek, can you try if 15 or 20 seconds 
would be enough? This timeout is currently hard-coded in _connect_to_selenium_server 
at line 285 of __init__.py. We can then adjust the timeout in 2.3.1.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=99#c13) by hano... on 23 Jun 2010_

I second radekw13's comment about the delay problem in Ubuntu, except that I am running 10.04. I've tried many things, including starting selenium as root without much luck. It freezes after the message "Started HttpContext[/,/]" and before "Started org.openqa.jetty.jetty.servlet.ServletHandler". The delay seems random, going anywhere from 1 to 5 minutes.

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=99#c14) by javierch... on 2 Jul 2013_

I have been following these tutorials on RF-seleniumLibrary automation:
<a href="http://www.wallix.org/2011/07/26/how-to-use-robotframework-with-the-selenium-library/" rel="nofollow">http://www.wallix.org/2011/07/26/how-to-use-robotframework-with-the-selenium-library/</a>
<a href="http://www.wallix.org/2011/09/06/how-to-use-robotframework-part-2/" rel="nofollow">http://www.wallix.org/2011/09/06/how-to-use-robotframework-part-2/</a>

When using the following parameters in file common.txt:

**\* Settings ***
Documentation  This resource file contains common and global variables
Library   SeleniumLibrary  25  localhost  

**\* Variables ***

# Choose Firefox Chrome Browser :

# Here you can change your web browser.

${browser}   googlechrome
${sel_speed}  0

Then run the test cases, I got following error:

Could not connect to Selenium Server in 120 seconds. Please make sure Selenium Server is running.

But, if just I use these parameters for library:
Library   SeleniumLibrary  25  localhost

... the test cases run as expected.

But also, if I use the following parameters:
Library   SeleniumLibrary  timeout=25  server_host=localhost  server_port=5556

The problem with the selenium server persists.

Of course that I have the selenium server up and running in all cases.

I'm using:
RobotFramework 2.7.5
SeleniumLibrary 2.9.1
Java jre 6_23

Maybe you can give me any hint on why the port parameter cannot be correctly recognized?

I-m a newbie with these tools, so probably this is a very basic error that I cannot see. Thanks,

**Comment by spooning** [comment]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=99#c15) by javierch... on 2 Jul 2013_

Forgot to mention that I am testing over Windows 7 O.S. I installed from source in all cases.

python version: 2.7.3
